
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Iamawinner10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
#spring.jpa.properties.hibernate.format.sql=true